name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Copy files to the server
        run: |
          npm install
          npm run build
          rsync -a --progress --human-readable --delete \
          --exclude-from '.gitignore' \
          --exclude .gitignore \
          --exclude .git \
          --exclude .next \
          --exclude ecosystem.config.js \
          . delawere2008@34.142.115.186:~/graphql-blog-demo/
      - name: Run app
        run: |
          ssh delawere2008@34.142.115.186 "cd ~/graphql-blog-demo && npm install --production
          # PM2
          # && NEXT_PUBLIC_HOST=true pm2 restart ecosystem.config.js --update-env"