name: eslint

on: 
  push: 
    branches: [master]
  
jobs: 
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
      - name: Install dependencies
        run: npm install
      - name: Prettify our source code with Prettier
        run: npm run check-format
      - uses: peterjgrainger/action-create-branch@v2.0.1
        if: ${{ failure() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ github.run_id }}
      - uses: actions/checkout@v2
        if: ${{ failure() }}
        with:
          ref: ${{ github.run_id }}
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        if: ${{ failure() }}
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Push changes
        if: ${{ failure() }}
        run: |
          npm install
          npm run format
          npm run check-format
          git add .
          git commit -m "format"
          git push -u origin ${{ github.run_id }}
      - name: Type checking in formatted branch
        if: ${{ failure() }}
        run: npm run check-types
      - name: Type checking in master branch
        uses: actions/checkout@v2
        if: ${{ success() }}
        with:
          ref: master
      - run: | 
          npm install
          npm run check-types