name: eslint

on: 
  push: 
    branches: [master]
  pull_request: 
    branches: '*'
  
jobs: 
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
      - name: Install dependencies
        run: npm install
      - name: Prettify our source code with Prettier
        run: npm run check-format
      - uses: peterjgrainger/action-create-branch@v2.0.1
        if: ${{ failure() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'formatted1'
      # - run: git checkout formatted
      # - run: npm run prettier --write
      # - run: git add .
      # - run: git commit -m "format"
      # - run: git push origin formatted